### ISSUE TITLE
Lint/Format fails in pysen because it does not support black v21.x series.

### ISSUE THREAD

**Issue by yaegassy** [yaegassy/coc-pysen#3]
Error (cli)
-------------------------------------------------------

## Format

```
(venv) pysen-check$ pysen run format
Running commands
Running: isort
Checking 1 files
Running: black
Checking 1 files
unexpected exception
Traceback (most recent call last):
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/runner.py", line 47, in run_cmd
    exit_code = cmd.run(reporter=r)
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/command.py", line 25, in run
    return self.__call__(reporter)
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/black.py", line 43, in __call__
    return black_wrapper.run(
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/ext/black_wrapper.py", line 79, in run
    _check_black_version()
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/ext/black_wrapper.py", line 64, in _check_black_version
    raise IncompatibleVersionError(
pysen.exceptions.IncompatibleVersionError: pysen only supports black versions: {19.10, 20.8}. version 21.4b2 is not supported.

 ** execution summary **
isort .......... OK (0.39 sec)
black .......... Failed (0.20 sec)

format finished with error(s)
Errored:
 - black
```

## Lint

```
(venv) pysen-check$ pysen run lint
Running commands concurrently...
... concurrent execution done
Running: black
Checking 1 files
unexpected exception
Traceback (most recent call last):
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/runner.py", line 47, in run_cmd
    exit_code = cmd.run(reporter=r)
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/command.py", line 25, in run
    return self.__call__(reporter)
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/black.py", line 43, in __call__
    return black_wrapper.run(
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/ext/black_wrapper.py", line 79, in run
    _check_black_version()
  File "/private/tmp/pysen-check/venv/lib/python3.9/site-packages/pysen/ext/black_wrapper.py", line 64, in _check_black_version
    raise IncompatibleVersionError(
pysen.exceptions.IncompatibleVersionError: pysen only supports black versions: {19.10, 20.8}. version 21.4b2 is not supported.
Running: flake8
Checking 1 files
Running: isort
Checking 1 files
Running: mypy
[1/1] Checking 1 entries
Success: no issues found in 1 source file

 ** execution summary **
isort .......... OK (0.59 sec)
black .......... Failed (0.38 sec)
flake8 .......... OK (0.51 sec)
mypy .......... OK (0.48 sec)

lint finished with error(s)
Errored:
 - black
```

Need to update the feature of pysen itself
-------------------------------------------------------

I'm sure this will be addressed in the next version of pysen, but just in case, you can use the workaround.

Of course, it is better to use the v20.8 series for the current situation.

### pysen/ext/black_wrapper.py

- <https://github.com/pfnet/pysen/blob/main/pysen/ext/black_wrapper.py#L57-L60>

**Before**:

```python
    compatible_versions = [
        VersionRepresentation(19, 10),
        VersionRepresentation(20, 8),
    ]
```

**After**:

```python
    compatible_versions = [
        VersionRepresentation(19, 10),
        VersionRepresentation(20, 8),
        VersionRepresentation(21, 4),
    ]
```

**Comment by yaegassy** [comment]
The `v0.1.2` version of "pysen-ls" has been released. This problem has been resolved. <https://pypi.org/project/pysen-ls/0.1.2/>
